# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Digital Leadership Lab
  
 
description: >- # this means to ignore newlines until "baseurl:"
  Strategic insights for CTOs and technology leaders. From code to strategy, platform thinking to digital transformation. Practical leadership wisdom for the modern tech executive.   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://som-nitjsr.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Just the Docs theme settings
just_the_docs:
  # Color scheme supports "light" (default) and "dark"
  color_scheme: light
  
  # Enable or disable the site title and search in the header
  search_enabled: true
  search:
    # Split pages into sections that can be searched individually
    heading_level: 2
    previews: 3
    preview_words_before: 5
    preview_words_after: 10
    tokenizer_separator: /[\s/\-]+/
    rel_url: true
    button: true
  
  # Enable or disable heading anchors
  heading_anchors: true
  
  # Enable or disable the back-to-top link
  back_to_top: true
  back_to_top_text: "Back to top"
  
  # Enable or disable the link to the repository
  gh_edit_link: false
  
  # Enable or disable the "last modified" date
  last_edit_timestamp: true
  
  # Enable or disable the "last modified" date format
  last_edit_date_format: "%B %d, %Y"
  
  # Enable or disable the footer
  footer_content: "Copyright &copy; 2025 Digital Leadership Lab. All rights reserved."
  
  # Enable or disable the search button
  search_button: true
  
  # Enable or disable the search results
  search_results: true
  
  # Enable or disable the search results preview
  search_results_preview: true
  
  # Enable or disable the search results preview words
  search_results_preview_words: 10
  
  # Enable or disable the search results preview words before
  search_results_preview_words_before: 5
  
  # Enable or disable the search results preview words after
  search_results_preview_words_after: 10